### ISSUE TITLE
fsutils.mkdir and fsutils.delete don't work on windows

### ISSUE THREAD

**Issue by TheKing0x9** [takase1121/lite-fsutils#1]
**Describe the problem**
In association with ```lite-contextmenu```, functions fsutils.mkdir and fsutils.delete on directories don't perform the required actions

**Steps To Reproduce**
- Install fsutils
- Install context-menu (I doubt though that the bug depends on this)
- Right Click on a folder 
- Click Create Folder
- Enter a folder name
- See that the folder is not created
- Right Click on any previously created folder
- Select Delete Folder
- See that the folder is not deleted

**Associated Information**
- Platform: Windows
- Lite XL version 1.16
- If I'm right, os.remove() does not delete directories on Windows, thus causing fsutils,delete on directories to not work.

**Suggested Fixes**
- I have a fix for fsutils.mkdir not working and will submit the PR soon
- fsutils.delete instead relies on os.remove() and hence the only way of fixing it will be to replace os.remove by system-specific commands (rmdir or rm -r).

**Comment by takase1121** [comment]
Wow, that's pain. No wonder people work with LFS.

**Comment by TheKing0x9** [comment]
Seriously 😅. I have submitted a fix for fsutils.mkdir
